/-
  Generated by extractor/generate_lean.py from data/equivalences.json.
  DO NOT EDIT BY HAND -- edit leanquantum_mapping.py or the extraction
  pipeline instead and regenerate.

  Source: Qiskit 2.5.1 StandardEquivalenceLibrary
  Generated: 2026-08-09T11:20:02.591954+00:00
  50 gates / 130 equivalences considered.

  See notes/coverage.md for a human-readable summary of what's proved,
  what's `sorry`, and what's blocked on a missing LeanQuantum definition.
-/

import Quantumlib.Data.Gate.Basic
import Quantumlib.Data.Gate.Rotate
import Quantumlib.Data.Gate.PhaseShift
import Quantumlib.Data.Gate.Pauli.Defs
import Quantumlib.Data.Gate.Equivs

namespace QiskitEquiv

-- NOTE: do NOT redeclare `π` notation here. LeanQuantum's own
-- Quantumlib/ForMathlib/Data/Complex/Basic.lean already declares
-- `notation "π" => Real.pi` globally (not `local`/`scoped`), pulled in
-- transitively via the imports above. Redeclaring it here creates a
-- second, competing notation for the same symbol, which is exactly what
-- produced every "Ambiguous term" elaboration error in the first
-- generated build -- Lean can't tell which `π` you mean.


/- ===== c3sx (4 qubit(s)) ===== -/

-- c3sx equivalence #0 (27 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cp: Diagonal -- likely safe, but verify.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * c3sx (source): Not yet triaged.
-- circuit: h() ; cp(0.39269908169872414) ; h() ; cx() ; h() ; cp(-0.39269908169872414) ; h() ; cx() ; h() ; cp(0.39269908169872414) ; h() ; cx() ; h() ; cp(-0.39269908169872414) ; h() ; cx() ; h() ; cp(0.39269908169872414) ; h() ; cx() ; h() ; cp(-0.39269908169872414) ; h() ; cx() ; h() ; cp(0.39269908169872414) ; h()

/- ===== ccx (3 qubit(s)) ===== -/

-- ccx equivalence #0 (15 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * tdg: Same pattern as sdg.
--   * ccx (source): Toffoli. `controlM` is single-control only; a doubly-controlled wrapper doesn't exist yet in LeanQuantum.
-- circuit: h() ; cx() ; tdg() ; cx() ; t() ; cx() ; tdg() ; cx() ; t() ; t() ; h() ; cx() ; t() ; tdg() ; cx()

-- ccx equivalence #1 (8 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * csx: Same ordering caveat as cx.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * ccx (source): Toffoli. `controlM` is single-control only; a doubly-controlled wrapper doesn't exist yet in LeanQuantum.
-- circuit: csx() ; cx() ; z() ; sdg() ; csx() ; z() ; cx() ; csx()

/- ===== ccz (3 qubit(s)) ===== -/

-- ccz equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * ccx: Toffoli. `controlM` is single-control only; a doubly-controlled wrapper doesn't exist yet in LeanQuantum.
--   * ccz (source): Same gap as ccx.
-- circuit: h() ; ccx() ; h()

/- ===== ch (2 qubit(s)) ===== -/

-- ch equivalence #0 (7 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * tdg: Same pattern as sdg.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * ch (source): Same ordering caveat as cx.
-- circuit: s() ; h() ; t() ; cx() ; tdg() ; h() ; sdg()

/- ===== cp (2 qubit(s)) ===== -/

-- cp equivalence #0 (5 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * cp (source): Diagonal -- likely safe, but verify.
-- circuit: p(0.5*ϴ) ; cx() ; p((-0.5)*ϴ) ; cx() ; p(0.5*ϴ)

-- cp equivalence #1 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cu1: Not yet triaged.
--   * cp (source): Diagonal -- likely safe, but verify.
-- circuit: cu1(ϴ)

-- cp equivalence #2 (3 instruction(s), global_phase=0.25*ϴ)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzz: Same as rxx.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * cp (source): Diagonal -- likely safe, but verify.
-- circuit: rzz((-0.5)*ϴ) ; rz(0.5*ϴ) ; rz(0.5*ϴ)

/- ===== crx (2 qubit(s)) ===== -/

-- crx equivalence #0 (5 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * crx (source): Same ordering caveat as cx.
-- circuit: s() ; cx() ; u((-0.5)*ϴ, 0.0, 0.0) ; cx() ; u(0.5*ϴ, -1.5707963267948966, 0.0)

-- crx equivalence #1 (6 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * crx (source): Same ordering caveat as cx.
-- circuit: s() ; cx() ; ry((-0.5)*ϴ) ; cx() ; ry(0.5*ϴ) ; sdg()

-- crx equivalence #2 (4 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * crx (source): Same ordering caveat as cx.
-- circuit: h() ; rx(0.5*ϴ) ; rxx((-0.5)*ϴ) ; h()

-- crx equivalence #3 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * crz: Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
--   * crx (source): Same ordering caveat as cx.
-- circuit: h() ; crz(ϴ) ; h()

/- ===== cry (2 qubit(s)) ===== -/

-- cry equivalence #0 (4 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * cry (source): Same ordering caveat as cx.
-- circuit: ry(0.5*ϴ) ; cx() ; ry((-0.5)*ϴ) ; cx()

-- cry equivalence #1 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * crz: Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
--   * cry (source): Same ordering caveat as cx.
-- circuit: rx(1.5707963267948966) ; crz(ϴ) ; rx(-1.5707963267948966)

-- cry equivalence #2 (5 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * crx: Same ordering caveat as cx.
--   * cry (source): Same ordering caveat as cx.
-- circuit: h() ; rz(1.5707963267948966) ; crx(ϴ) ; rz(-1.5707963267948966) ; h()

-- cry equivalence #3 (6 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * rzz: Same as rxx.
--   * cry (source): Same ordering caveat as cx.
-- circuit: sdg() ; rx(0.5*ϴ) ; h() ; rzz((-0.5)*ϴ) ; h() ; s()

/- ===== crz (2 qubit(s)) ===== -/

-- crz equivalence #0 (4 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * crz (source): Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
-- circuit: rz(0.5*ϴ) ; cx() ; rz((-0.5)*ϴ) ; cx()

-- crz equivalence #1 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cry: Same ordering caveat as cx.
--   * crz (source): Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
-- circuit: rx(-1.5707963267948966) ; cry(ϴ) ; rx(1.5707963267948966)

-- crz equivalence #2 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * crx: Same ordering caveat as cx.
--   * crz (source): Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
-- circuit: h() ; crx(ϴ) ; h()

-- crz equivalence #3 (2 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rzz: Same as rxx.
--   * crz (source): Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
-- circuit: rz(0.5*ϴ) ; rzz((-0.5)*ϴ)

/- ===== cs (2 qubit(s)) ===== -/

-- cs equivalence #0 (5 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * tdg: Same pattern as sdg.
--   * cs (source): Diagonal -- likely safe, but verify.
-- circuit: t() ; t() ; cx() ; tdg() ; cx()

-- cs equivalence #1 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * csx: Same ordering caveat as cx.
--   * cs (source): Diagonal -- likely safe, but verify.
-- circuit: h() ; csx() ; h()

/- ===== csdg (2 qubit(s)) ===== -/

-- csdg equivalence #0 (5 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * tdg: Same pattern as sdg.
--   * csdg (source): Diagonal -- likely safe, but verify.
-- circuit: cx() ; t() ; cx() ; tdg() ; tdg()

-- csdg equivalence #1 (4 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * csx: Same ordering caveat as cx.
--   * csdg (source): Diagonal -- likely safe, but verify.
-- circuit: h() ; cx() ; csx() ; h()

/- ===== cswap (3 qubit(s)) ===== -/

-- cswap equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * ccx: Toffoli. `controlM` is single-control only; a doubly-controlled wrapper doesn't exist yet in LeanQuantum.
--   * cswap (source): Fredkin; no 3-qubit control primitive yet.
-- circuit: cx() ; ccx() ; cx()

/- ===== csx (2 qubit(s)) ===== -/

-- csx equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cs: Diagonal -- likely safe, but verify.
--   * csx (source): Same ordering caveat as cx.
-- circuit: h() ; cs() ; h()

-- csx equivalence #1 (5 instruction(s), global_phase=0.7853981633974483)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzx: Same as rxx.
--   * tdg: Same pattern as sdg.
--   * csx (source): Same ordering caveat as cx.
-- circuit: x() ; rzx(0.7853981633974483) ; tdg() ; x() ; rx(0.7853981633974483)

/- ===== cu (2 qubit(s)) ===== -/

-- cu equivalence #0 (7 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * cu (source): 4-parameter controlled-U; needs controlM applied to `rotate` plus a global phase factor, not yet composed.
-- circuit: p(γ) ; p(0.5*(λ + φ)) ; p(0.5*(λ - φ)) ; cx() ; u((-0.5)*ϴ, 0.0, (-0.5)*(λ + φ)) ; cx() ; u(0.5*ϴ, φ, 0.0)

-- cu equivalence #1 (2 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   * cu3: Not yet triaged.
--   * cu (source): 4-parameter controlled-U; needs controlM applied to `rotate` plus a global phase factor, not yet composed.
-- circuit: p(γ) ; cu3(ϴ, φ, λ)

/- ===== cu1 (2 qubit(s)) ===== -/

-- cu1 equivalence #0 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * cu1 (source): Not yet triaged.
-- circuit: p(0.5*λ) ; cx() ; p((-0.5)*λ) ; cx() ; p(0.5*λ)

/- ===== cu3 (2 qubit(s)) ===== -/

-- cu3 equivalence #0 (6 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * cu3 (source): Not yet triaged.
-- circuit: p(0.5*(λ + φ)) ; p(0.5*(λ - φ)) ; cx() ; u((-0.5)*ϴ, 0.0, (-0.5)*(λ + φ)) ; cx() ; u(0.5*ϴ, φ, 0.0)

-- cu3 equivalence #1 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cu: 4-parameter controlled-U; needs controlM applied to `rotate` plus a global phase factor, not yet composed.
--   * cu3 (source): Not yet triaged.
-- circuit: cu(ϴ, φ, λ, 0.0)

/- ===== cx (2 qubit(s)) ===== -/

-- cx equivalence #0 (4 instruction(s), global_phase=0.7853981633974483)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
--   * ecr: Echoed cross-resonance; hardware-native gate, no LeanQuantum analogue.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: sdg() ; sxdg() ; ecr() ; x()

-- cx equivalence #1 (5 instruction(s), global_phase=5.497787143782138)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: ry(-1.5707963267948966) ; rxx(-1.5707963267948966) ; rx(1.5707963267948966) ; rx(-1.5707963267948966) ; ry(1.5707963267948966)

-- cx equivalence #2 (5 instruction(s), global_phase=0.7853981633974483)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: ry(-1.5707963267948966) ; rxx(1.5707963267948966) ; rx(-1.5707963267948966) ; rx(1.5707963267948966) ; ry(1.5707963267948966)

-- cx equivalence #3 (5 instruction(s), global_phase=0.7853981633974483)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: ry(1.5707963267948966) ; rxx(-1.5707963267948966) ; rx(1.5707963267948966) ; rx(1.5707963267948966) ; ry(-1.5707963267948966)

-- cx equivalence #4 (5 instruction(s), global_phase=5.497787143782138)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: ry(1.5707963267948966) ; rxx(1.5707963267948966) ; rx(-1.5707963267948966) ; rx(-1.5707963267948966) ; ry(-1.5707963267948966)

-- cx equivalence #5 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cz: Diagonal, so ordering is probably safe, but verify -- don't assume from cx.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: h() ; cz() ; h()

-- cx equivalence #6 (13 instruction(s), global_phase=2.356194490192345)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * iswap: No LeanQuantum analogue yet.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: h() ; x() ; h() ; iswap() ; x() ; x() ; h() ; iswap() ; h() ; s() ; s() ; x() ; h()

-- cx equivalence #7 (4 instruction(s), global_phase=5.497787143782138)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * ecr: Echoed cross-resonance; hardware-native gate, no LeanQuantum analogue.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: rz(-1.5707963267948966) ; ry(3.141592653589793) ; rx(1.5707963267948966) ; ecr()

-- cx equivalence #8 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * cp: Diagonal -- likely safe, but verify.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: u(1.5707963267948966, 0.0, 3.141592653589793) ; cp(3.141592653589793) ; u(1.5707963267948966, 0.0, 3.141592653589793)

-- cx equivalence #9 (4 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * crz: Compounds the rz derived-phase issue AND the ordering issue -- resolve both before attempting a proof.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: u(1.5707963267948966, 0.0, 3.141592653589793) ; u(0.0, 0.0, 1.5707963267948966) ; crz(3.141592653589793) ; u(1.5707963267948966, 0.0, 3.141592653589793)

-- cx equivalence #10 (3 instruction(s), global_phase=0.7853981633974483)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzx: Same as rxx.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
--   * cx (source): IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
-- circuit: rzx(1.5707963267948966) ; sdg() ; sxdg()

/- ===== cy (2 qubit(s)) ===== -/

-- cy equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * cy (source): Same ordering caveat as cx.
-- circuit: sdg() ; cx() ; s()

/- ===== cz (2 qubit(s)) ===== -/

-- cz equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * cz (source): Diagonal, so ordering is probably safe, but verify -- don't assume from cx.
-- circuit: h() ; cx() ; h()

/- ===== dcx (2 qubit(s)) ===== -/

-- dcx equivalence #0 (2 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * dcx (source): Double-CNOT; expressible as cnot-notc composition once cx ordering is resolved.
-- circuit: cx() ; cx()

-- dcx equivalence #1 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * iswap: No LeanQuantum analogue yet.
--   * dcx (source): Double-CNOT; expressible as cnot-notc composition once cx ordering is resolved.
-- circuit: h() ; sdg() ; sdg() ; iswap() ; h()

/- ===== ecr (2 qubit(s)) ===== -/

-- ecr equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzx: Same as rxx.
--   * ecr (source): Echoed cross-resonance; hardware-native gate, no LeanQuantum analogue.
-- circuit: rzx(0.7853981633974483) ; x() ; rzx(-0.7853981633974483)

-- ecr equivalence #1 (4 instruction(s), global_phase=5.497787143782138)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * ecr (source): Echoed cross-resonance; hardware-native gate, no LeanQuantum analogue.
-- circuit: s() ; sx() ; cx() ; x()

/- ===== h (1 qubit(s)) ===== -/

-- h equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
lemma h_equiv_0 :
    hadamard = rotate (π / 2) 0 π := by
  rw [rotate_hadamard]

-- h equivalence #1 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u2: u2(phi,lam) = U(pi/2, phi, lam).
lemma h_equiv_1 :
    hadamard = rotate (π / 2) 0 π := by
  sorry

-- h equivalence #2 (3 instruction(s), global_phase=5.497787143782138)
-- TODO_PROOF (direct mapping)
--   note: sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
lemma h_equiv_2 :
    hadamard = (Complex.exp (((7 * π / 4)) * Complex.I)) • (sGate * sqrtx * sGate) := by
  sorry

-- h equivalence #3 (3 instruction(s), global_phase=0.7853981633974483)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
-- circuit: sdg() ; sxdg() ; sdg()

-- h equivalence #4 (2 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma h_equiv_4 :
    hadamard = (Complex.exp ((π / 2) * Complex.I)) • (xRotate π * yRotate (π / 2)) := by
  sorry

-- h equivalence #5 (2 instruction(s), global_phase=1.5707963267948966)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * r: Qiskit's r(theta, phi) has no direct LeanQuantum primitive; it's a rotation about an axis in the XY-plane. Expressible via `rotate`-family composition but needs a derivation, not a lookup.
-- circuit: r(1.5707963267948966, 1.5707963267948966) ; r(3.141592653589793, 0.0)

/- ===== id (1 qubit(s)) ===== -/

-- id equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   note: id (source): Identity matrix, Mathlib's `1 : CSquare 2`.
lemma id_equiv_0 :
    1 = rotate 0 0 0 := by
  exact rotate_one.symm

-- id equivalence #1 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: id (source): Identity matrix, Mathlib's `1 : CSquare 2`.
lemma id_equiv_1 :
    1 = xRotate 0 := by
  solve_matrix [xRotate]

-- id equivalence #2 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: id (source): Identity matrix, Mathlib's `1 : CSquare 2`.
lemma id_equiv_2 :
    1 = yRotate 0 := by
  solve_matrix [yRotate]

-- id equivalence #3 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   note: id (source): Identity matrix, Mathlib's `1 : CSquare 2`.
lemma id_equiv_3 :
    1 = phaseShift 0 := by
  exact phaseShift_zero.symm

/- ===== iswap (2 qubit(s)) ===== -/

-- iswap equivalence #0 (6 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * iswap (source): No LeanQuantum analogue yet.
-- circuit: s() ; s() ; h() ; cx() ; cx() ; h()

/- ===== p (1 qubit(s)) ===== -/

-- p equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u1: u1(lambda) = p(lambda), same as p.
--   note: p (source): Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
lemma p_equiv_0 (ϴ : ℝ) :
    phaseShift (ϴ) = phaseShift (ϴ) := by
  rfl

-- p equivalence #1 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   note: p (source): Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
lemma p_equiv_1 (ϴ : ℝ) :
    phaseShift (ϴ) = rotate 0 0 (ϴ) := by
  rw [rotate_phaseShift]

/- ===== r (1 qubit(s)) ===== -/

-- r equivalence #0 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * r (source): Qiskit's r(theta, phi) has no direct LeanQuantum primitive; it's a rotation about an axis in the XY-plane. Expressible via `rotate`-family composition but needs a derivation, not a lookup.
-- circuit: u(ϴ, -1.5707963267948966 + φ, 1.5707963267948966 - φ)

/- ===== rcccx (4 qubit(s)) ===== -/

-- rcccx equivalence #0 (18 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * tdg: Same pattern as sdg.
--   * rcccx (source): Relative-phase Toffoli variant, no analogue.
-- circuit: h() ; t() ; cx() ; tdg() ; h() ; cx() ; t() ; cx() ; tdg() ; cx() ; t() ; cx() ; tdg() ; h() ; t() ; cx() ; tdg() ; h()

/- ===== rccx (3 qubit(s)) ===== -/

-- rccx equivalence #0 (9 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * tdg: Same pattern as sdg.
--   * rccx (source): Relative-phase Toffoli variant, no analogue.
-- circuit: h() ; t() ; cx() ; tdg() ; cx() ; t() ; cx() ; tdg() ; h()

/- ===== rx (1 qubit(s)) ===== -/

-- rx equivalence #0 (3 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
lemma rx_equiv_0 (ϴ : ℝ) :
    xRotate (ϴ) = hadamard * phaseShift (ϴ) * hadamard := by
  sorry

-- rx equivalence #1 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * r: Qiskit's r(theta, phi) has no direct LeanQuantum primitive; it's a rotation about an axis in the XY-plane. Expressible via `rotate`-family composition but needs a derivation, not a lookup.
-- circuit: r(ϴ, 0.0)

/- ===== rxx (2 qubit(s)) ===== -/

-- rxx equivalence #0 (7 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rxx (source): Ising coupling gate; not expressible via controlM (no single control qubit).
-- circuit: h() ; h() ; cx() ; rz(ϴ) ; cx() ; h() ; h()

-- rxx equivalence #1 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzx: Same as rxx.
--   * rxx (source): Ising coupling gate; not expressible via controlM (no single control qubit).
-- circuit: h() ; rzx(ϴ) ; h()

-- rxx equivalence #2 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzz: Same as rxx.
--   * rxx (source): Ising coupling gate; not expressible via controlM (no single control qubit).
-- circuit: h() ; h() ; rzz(ϴ) ; h() ; h()

/- ===== ry (1 qubit(s)) ===== -/

-- ry equivalence #0 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * r: Qiskit's r(theta, phi) has no direct LeanQuantum primitive; it's a rotation about an axis in the XY-plane. Expressible via `rotate`-family composition but needs a derivation, not a lookup.
-- circuit: r(ϴ, 1.5707963267948966)

-- ry equivalence #1 (3 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma ry_equiv_1 (ϴ : ℝ) :
    yRotate (ϴ) = sGate * xRotate (ϴ) * phaseShift (-(π / 2)) := by
  sorry

/- ===== ryy (2 qubit(s)) ===== -/

-- ryy equivalence #0 (7 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * ryy (source): Same as rxx.
-- circuit: rx(1.5707963267948966) ; rx(1.5707963267948966) ; cx() ; rz(ϴ) ; cx() ; rx(-1.5707963267948966) ; rx(-1.5707963267948966)

-- ryy equivalence #1 (7 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * ryy (source): Same as rxx.
-- circuit: sxdg() ; sxdg() ; cx() ; rz(ϴ) ; cx() ; sx() ; sx()

-- ryy equivalence #2 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzz: Same as rxx.
--   * ryy (source): Same as rxx.
-- circuit: rx(1.5707963267948966) ; rx(1.5707963267948966) ; rzz(ϴ) ; rx(-1.5707963267948966) ; rx(-1.5707963267948966)

-- ryy equivalence #3 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * ryy (source): Same as rxx.
-- circuit: sdg() ; sdg() ; rxx(ϴ) ; s() ; s()

/- ===== rz (1 qubit(s)) ===== -/

-- rz equivalence #0 (1 instruction(s), global_phase=(-0.5)*λ)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   note: rz (source): Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   note: symbolic global_phase '(-0.5)*λ' -- verify this substitution parses.
lemma rz_equiv_0 (lam : ℝ) :
    (Complex.exp ((-0.5 * lam) * Complex.I)) • (phaseShift lam) = (Complex.exp (((-0.5)*lam) * Complex.I)) • (phaseShift lam) := by
  congr 2


-- rz equivalence #1 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
--   * rz (source): Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
-- circuit: sx() ; ry(-λ) ; sxdg()

-- rz equivalence #2 (3 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: rz (source): Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
lemma rz_equiv_2 (lam : ℝ) :
    (Complex.exp ((-0.5 * lam) * Complex.I)) • (phaseShift lam) = hadamard * xRotate lam * hadamard := by
  unfold phaseShift
  rw [Complex.exp_mul_I]
  solve_matrix [hadamard, xRotate]

/- ===== rzx (2 qubit(s)) ===== -/

-- rzx equivalence #0 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rzx (source): Same as rxx.
-- circuit: h() ; cx() ; rz(ϴ) ; cx() ; h()

-- rzx equivalence #1 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzz: Same as rxx.
--   * rzx (source): Same as rxx.
-- circuit: h() ; rzz(ϴ) ; h()

-- rzx equivalence #2 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rzx (source): Same as rxx.
-- circuit: h() ; cx() ; rz(ϴ) ; cx() ; h()

/- ===== rzz (2 qubit(s)) ===== -/

-- rzz equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rzz (source): Same as rxx.
-- circuit: cx() ; rz(ϴ) ; cx()

-- rzz equivalence #1 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * rzz (source): Same as rxx.
-- circuit: h() ; h() ; rxx(ϴ) ; h() ; h()

-- rzz equivalence #2 (3 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rzx: Same as rxx.
--   * rzz (source): Same as rxx.
-- circuit: h() ; rzx(ϴ) ; h()

-- rzz equivalence #3 (3 instruction(s), global_phase=0.5*ϴ)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * cp: Diagonal -- likely safe, but verify.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rzz (source): Same as rxx.
-- circuit: cp((-2)*ϴ) ; rz(ϴ) ; rz(ϴ)

-- rzz equivalence #4 (5 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * ryy: Same as rxx.
--   * rzz (source): Same as rxx.
-- circuit: rx(-1.5707963267948966) ; rx(-1.5707963267948966) ; ryy(ϴ) ; rx(1.5707963267948966) ; rx(1.5707963267948966)

/- ===== s (1 qubit(s)) ===== -/

-- s equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
lemma s_equiv_0 :
    sGate = phaseShift (π / 2) := by
  rfl

-- s equivalence #1 (2 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
lemma s_equiv_1 :
    sGate = tGate * tGate := by
  exact tGate_mul_tGate.symm

/- ===== sdg (1 qubit(s)) ===== -/

-- sdg equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   note: sdg (source): = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma sdg_equiv_0 :
    phaseShift (-(π / 2)) = phaseShift (-π / 2) := by
  sorry

-- sdg equivalence #1 (2 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: sdg (source): = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma sdg_equiv_1 :
    phaseShift (-(π / 2)) = σz * sGate := by
  sorry

-- sdg equivalence #2 (2 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: sdg (source): = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma sdg_equiv_2 :
     phaseShift (-(π / 2)) = sGate * σz := by
  sorry

-- sdg equivalence #3 (3 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: sdg (source): = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma sdg_equiv_3 :
    phaseShift (-(π / 2)) = sGate * sGate * sGate := by
  sorry

-- sdg equivalence #4 (2 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: tdg: Same pattern as sdg.
--   note: sdg (source): = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma sdg_equiv_4 :
    phaseShift (-(π / 2)) = phaseShift (-(π / 4)) * phaseShift (-(π / 4)) := by
  sorry

/- ===== swap (2 qubit(s)) ===== -/

-- swap equivalence #0 (3 instruction(s), global_phase=0.0)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * swap (source): Matrix shape matches but qubit-index ordering not yet verified the way cx/cnot was — see cx entry below.
-- circuit: cx() ; cx() ; cx()

-- swap equivalence #1 (9 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * ecr: Echoed cross-resonance; hardware-native gate, no LeanQuantum analogue.
--   * swap (source): Matrix shape matches but qubit-index ordering not yet verified the way cx/cnot was — see cx entry below.
-- circuit: rz(-1.5707963267948966) ; sx() ; ecr() ; rz(-1.5707963267948966) ; sx() ; ecr() ; rz(-1.5707963267948966) ; sx() ; ecr()

-- swap equivalence #2 (9 instruction(s), global_phase=4.71238898038469)
-- BLOCKED (unverified qubit-ordering / convention) -- not emitted as a lemma, see notes above.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * cz: Diagonal, so ordering is probably safe, but verify -- don't assume from cx.
--   * swap (source): Matrix shape matches but qubit-index ordering not yet verified the way cx/cnot was — see cx entry below.
-- circuit: sx() ; sx() ; cz() ; sx() ; sx() ; cz() ; sx() ; sx() ; cz()

/- ===== sx (1 qubit(s)) ===== -/

-- sx equivalence #0 (3 instruction(s), global_phase=0.7853981633974483)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   note: sx (source): Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
lemma sx_equiv_0 :
    sqrtx = (Complex.exp ((π / 4) * Complex.I)) • (phaseShift (-(π / 2)) * hadamard * phaseShift (-(π / 2))) := by
  sorry

-- sx equivalence #1 (1 instruction(s), global_phase=0.7853981633974483)
-- TODO_PROOF (direct mapping)
--   note: sx (source): Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
lemma sx_equiv_1 :
    sqrtx = (Complex.exp ((π / 4) * Complex.I)) • (xRotate (π / 2)) := by
  sorry

/- ===== sxdg (1 qubit(s)) ===== -/

-- sxdg equivalence #0 (3 instruction(s), global_phase=5.497787143782138)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sxdg (source): sqrtx⁻¹ = sqrtxᴴ, no named def yet.
-- circuit: s() ; h() ; s()

-- sxdg equivalence #1 (1 instruction(s), global_phase=5.497787143782138)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * sxdg (source): sqrtx⁻¹ = sqrtxᴴ, no named def yet.
-- circuit: rx(-1.5707963267948966)

/- ===== t (1 qubit(s)) ===== -/

-- t equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
lemma t_equiv_0 :
    tGate = phaseShift (π / 4) := by
  rfl

-- t equivalence #1 (3 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: tdg: Same pattern as sdg.
--   note: sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma t_equiv_1 :
    tGate = phaseShift (-(π / 4)) * phaseShift (-(π / 2)) * σz := by
  unfold tGate
  rw [← phaseShift_π, phaseShift_mul_phaseShift, phaseShift_mul_phaseShift]
  congr 1
  ring
/- ===== tdg (1 qubit(s)) ===== -/

-- tdg equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   note: tdg (source): Same pattern as sdg.
lemma tdg_equiv_0 :
    phaseShift (-(π / 4)) = phaseShift (-π / 4) := by
  sorry

-- tdg equivalence #1 (3 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: tdg (source): Same pattern as sdg.
lemma tdg_equiv_1 :
    phaseShift (-(π / 4)) = σz * sGate * tGate := by
  sorry

/- ===== u (1 qubit(s)) ===== -/

-- u equivalence #0 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * u3: Not yet triaged.
--   * u (source): Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
-- circuit: u3(ϴ, φ, λ)

/- ===== u1 (1 qubit(s)) ===== -/

-- u1 equivalence #0 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * u3: Not yet triaged.
--   * u1 (source): u1(lambda) = p(lambda), same as p.
-- circuit: u3(0.0, 0.0, λ)

-- u1 equivalence #1 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
--   note: u1 (source): u1(lambda) = p(lambda), same as p.
lemma u1_equiv_1 (lam : ℝ) :
    phaseShift lam = phaseShift lam := by
  rfl

-- u1 equivalence #2 (1 instruction(s), global_phase=0.5*λ)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   note: u1 (source): u1(lambda) = p(lambda), same as p.
--   note: symbolic global_phase '0.5*λ' -- verify this substitution parses.
lemma u1_equiv_2 (lam : ℝ) :
    phaseShift lam = (Complex.exp ((0.5*lam) * Complex.I)) • ((Complex.exp ((-0.5 * lam) * Complex.I)) • (phaseShift lam)) := by
  rw [smul_smul, ← Complex.exp_add, show (0.5*lam)*Complex.I + (-0.5*lam)*Complex.I = 0 by ring, Complex.exp_zero, one_smul]

/- ===== u2 (1 qubit(s)) ===== -/

-- u2 equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   note: u2 (source): u2(phi,lam) = U(pi/2, phi, lam).
lemma u2_equiv_0 (φ : ℝ) (lam : ℝ) :
    rotate (π / 2) (φ) lam = rotate (π / 2) (φ) lam := by
  rfl

-- u2 equivalence #1 (3 instruction(s), global_phase=5.497787143782138)
-- TODO_PROOF (direct mapping)
--   note: u1: u1(lambda) = p(lambda), same as p.
--   note: sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   note: u2 (source): u2(phi,lam) = U(pi/2, phi, lam).
lemma u2_equiv_1 (φ : ℝ) (lam : ℝ) :
    rotate (π / 2) (φ) lam = (Complex.exp (((7 * π / 4)) * Complex.I)) • (phaseShift ((π / 2) + φ) * sqrtx * phaseShift ((-π / 2) + lam)) := by
  sorry

/- ===== u3 (1 qubit(s)) ===== -/

-- u3 equivalence #0 (5 instruction(s), global_phase=0.5*(λ + φ - 3.141592653589793))
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * u3 (source): Not yet triaged.
-- circuit: rz(λ) ; sx() ; rz(3.141592653589793 + ϴ) ; sx() ; rz(9.42477796076938 + φ)

-- u3 equivalence #1 (1 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
--   * u3 (source): Not yet triaged.
-- circuit: u(ϴ, φ, λ)

/- ===== x (1 qubit(s)) ===== -/

-- x equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
lemma x_equiv_0 :
    σx = rotate π 0 π := by
  exact rotate_σx.symm

-- x equivalence #1 (4 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
lemma x_equiv_1 :
    σx = hadamard * sGate * sGate * hadamard := by
  sorry

-- x equivalence #2 (2 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma x_equiv_2 :
    σx = (Complex.exp ((π / 2) * Complex.I)) • (σz * σy) := by
  rw [σz_mul_σy, Complex.exp_pi_div_two_mul_I, smul_smul]
  norm_num [Complex.I_sq]

-- x equivalence #3 (1 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma x_equiv_3 :
    σx = (Complex.exp ((π / 2) * Complex.I)) • (xRotate π) := by
  sorry

/- ===== xx_minus_yy (2 qubit(s)) ===== -/

-- xx_minus_yy equivalence #0 (14 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
--   * xx_minus_yy (source): Not yet triaged.
-- circuit: rz(-β) ; rz(-1.5707963267948966) ; sx() ; rz(1.5707963267948966) ; s() ; cx() ; ry(0.5*ϴ) ; ry((-0.5)*ϴ) ; cx() ; sdg() ; rz(-1.5707963267948966) ; sxdg() ; rz(1.5707963267948966) ; rz(β)

-- xx_minus_yy equivalence #1 (4 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * ryy: Same as rxx.
--   * xx_minus_yy (source): Not yet triaged.
-- circuit: rz(-β) ; rxx(0.5*ϴ) ; ryy((-0.5)*ϴ) ; rz(β)

/- ===== xx_plus_yy (2 qubit(s)) ===== -/

-- xx_plus_yy equivalence #0 (14 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * sx: Verified: Qiskit SXGate() == LeanQuantum sqrtx exactly, no global phase correction needed (checked numerically).
--   * cx: IMPORTANT: numerically, Qiskit's CXGate() (little-endian Operator convention, qubit 0 = control) matches LeanQuantum's `notc`, NOT `cnot`, because Qiskit's qubit-index-to-tensor-factor ordering is the reverse of the naive reading. Do not assume cx -> cnot just because the names look aligned. This needs to be re-derived from LeanQuantum's own Fin-indexing convention (not just eyeballing the matrix) before it's trusted -- see notes/qubit_ordering.md.
--   * sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
--   * sxdg: sqrtx⁻¹ = sqrtxᴴ, no named def yet.
--   * xx_plus_yy (source): Not yet triaged.
-- circuit: rz(β) ; rz(-1.5707963267948966) ; sx() ; rz(1.5707963267948966) ; s() ; cx() ; ry((-0.5)*ϴ) ; ry((-0.5)*ϴ) ; cx() ; sdg() ; rz(-1.5707963267948966) ; sxdg() ; rz(1.5707963267948966) ; rz(-β)

-- xx_plus_yy equivalence #1 (4 instruction(s), global_phase=0.0)
-- BLOCKED (missing LeanQuantum definition(s)) -- not emitted as a lemma, see notes above.
--   * rz: Verified: Qiskit RZGate(theta) == exp(-i*theta/2) * phaseShift(theta) exactly. Needs a `rzGate` def (or a scalar-multiple lemma) in LeanQuantum before equivalence lemmas can cite it directly.
--   * rxx: Ising coupling gate; not expressible via controlM (no single control qubit).
--   * ryy: Same as rxx.
--   * xx_plus_yy (source): Not yet triaged.
-- circuit: rz(β) ; rxx(0.5*ϴ) ; ryy(0.5*ϴ) ; rz(-β)

/- ===== y (1 qubit(s)) ===== -/

-- y equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: u: Verified: Qiskit U(theta,phi,lambda) == LeanQuantum rotate(theta,phi,delta) exactly, param-for-param, no phase correction. This is the load-bearing identity: most other single-qubit equivalences bottom out at U.
lemma y_equiv_0 :
    σy = rotate π (π / 2) (π / 2) := by
  exact rotate_σy.symm

-- y equivalence #1 (6 instruction(s), global_phase=4.71238898038469)
-- TODO_PROOF (direct mapping)
lemma y_equiv_1 :
    σy = (Complex.exp (((3 * π / 2)) * Complex.I)) • (sGate * sGate * hadamard * sGate * sGate * hadamard) := by
  sorry

-- y equivalence #2 (6 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma y_equiv_2 :
    σy = (Complex.exp ((π / 2) * Complex.I)) • (hadamard * sGate * sGate * hadamard * sGate * sGate) := by
  sorry

-- y equivalence #3 (2 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma y_equiv_3 :
    σy = (Complex.exp ((π / 2) * Complex.I)) • (σx * σz) := by
  rw [σx_mul_σz, Complex.exp_pi_div_two_mul_I, smul_smul]
  norm_num [Complex.I_sq]

-- y equivalence #4 (1 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma y_equiv_4 :
    σy = (Complex.exp ((π / 2) * Complex.I)) • (yRotate π) := by
  sorry

/- ===== z (1 qubit(s)) ===== -/

-- z equivalence #0 (1 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
--   note: p: Verified: Qiskit PhaseGate(lambda) == phaseShift(lambda) exactly.
lemma z_equiv_0 :
    σz = phaseShift π := by
  exact phaseShift_π.symm

-- z equivalence #1 (2 instruction(s), global_phase=0.0)
-- TODO_PROOF (direct mapping)
lemma z_equiv_1 :
    σz = sGate * sGate := by
  exact sGate_mul_sGate.symm

-- z equivalence #2 (2 instruction(s), global_phase=0.0)
-- TODO_PROOF (derived -- needs helper lemma first)
--   note: sdg: = sGate⁻¹; sGate is unitary so sGate⁻¹ = sGateᴴ. Either prove via phaseShift_mul_phaseShift or add sdgGate.
lemma z_equiv_2 :
    σz = phaseShift (-(π / 2)) * phaseShift (-(π / 2)) := by
  sorry

-- z equivalence #3 (2 instruction(s), global_phase=1.5707963267948966)
-- TODO_PROOF (direct mapping)
lemma z_equiv_3 :
    σz = (Complex.exp ((π / 2) * Complex.I)) • (σy * σx) := by
  rw [σy_mul_σx, Complex.exp_pi_div_two_mul_I, smul_smul]
  norm_num [Complex.I_sq]


end QiskitEquiv
