"""
generate_coverage.py

Turns data/equivalences.json + leanquantum_mapping.py into
notes/coverage.md: a plain-English status report of what's provable
right now, what's one helper-lemma away, and what's genuinely blocked
(missing LeanQuantum primitive, or unverified convention).

Run this after extract_equivalences.py and before generate_lean.py so
the coverage numbers and the generated Lean file always agree.
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

from leanquantum_mapping import resolve

STATUS_LABEL = {
    "direct": "Ready to attempt proof (direct mapping, numerically verified)",
    "derived": "Needs one helper lemma first (verified relationship, not yet in LeanQuantum)",
    "needs_convention_check": "Blocked: candidate mapping exists but qubit-ordering unverified",
    "needs_def": "Blocked: no LeanQuantum primitive exists yet",
}


def worst_status_for_equivalence(gate: dict, eq: dict) -> str:
    rank = {"direct": 0, "derived": 1, "needs_convention_check": 2, "needs_def": 3}
    worst = resolve(gate["name"]).status
    for instr in eq["instructions"]:
        s = resolve(instr["name"]).status
        if rank[s] > rank[worst]:
            worst = s
    return worst


def main() -> None:
    data_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("data/equivalences.json")
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("notes/coverage.md")

    manifest = json.loads(data_path.read_text())

    per_gate_status: dict[str, str] = {}
    counts = Counter()
    by_status_examples: dict[str, list[str]] = defaultdict(list)

    for gate in manifest["gates"]:
        best_for_gate = "needs_def"
        rank = {"direct": 0, "derived": 1, "needs_convention_check": 2, "needs_def": 3}
        for eq in gate["equivalences"]:
            s = worst_status_for_equivalence(gate, eq)
            counts[s] += 1
            if rank[s] < rank[best_for_gate]:
                best_for_gate = s
            if len(by_status_examples[s]) < 3:
                by_status_examples[s].append(f"`{gate['name']}` equivalence #{eq['index']}")
        per_gate_status[gate["name"]] = best_for_gate

    total = sum(counts.values())

    lines = [
        "# Coverage report",
        "",
        f"Generated from Qiskit `{manifest['qiskit_version']}` "
        f"StandardEquivalenceLibrary ({manifest['gate_count']} gates, "
        f"{total} total equivalences).",
        "",
        "This is regenerated by `extractor/generate_coverage.py` every time the "
        "extraction runs — don't edit by hand.",
        "",
        "## Summary",
        "",
        "| Status | Count | % | Meaning |",
        "|---|---|---|---|",
    ]
    for status in ("direct", "derived", "needs_convention_check", "needs_def"):
        c = counts[status]
        pct = 100 * c / total if total else 0
        lines.append(f"| {status} | {c} | {pct:.0f}% | {STATUS_LABEL[status]} |")

    lines += [
        "",
        "## What this means in practice",
        "",
        f"- **{counts['direct']} equivalences** ({100*counts['direct']/total:.0f}%) have every "
        "gate mapped to an existing LeanQuantum matrix with a numerically-verified, "
        "phase-correct convention. These are genuinely ready for someone to sit down "
        "and try to close the `sorry`. Several of them (the `h` gate's U-gate and "
        "`u2` decompositions) restate lemmas LeanQuantum already has, just from the "
        "opposite direction, which is a promising sign the two matrix conventions "
        "were built compatibly by coincidence.",
        f"- **{counts['derived']} equivalences** need exactly one small helper lemma "
        "first (mainly the `rz = exp(-iθ/2) • phaseShift(θ)` relationship, and the "
        "`sdg`/`tdg` inverse-gate relationships) before they become 'direct'-tier.",
        f"- **{counts['needs_convention_check']} equivalences** are blocked on the "
        "cx/cnot-vs-notc qubit-ordering question — see `notes/qubit_ordering.md`. "
        "This single open question gates a disproportionate number of two-qubit "
        "equivalences, so it's the highest-leverage thing to resolve first.",
        f"- **{counts['needs_def']} equivalences** need genuinely new LeanQuantum "
        "definitions (multi-controlled gates, the Ising-coupling family "
        "rxx/ryy/rzz/rzx, hardware-native gates like ecr). These are real "
        "contributions to LeanQuantum itself, not just bridge work.",
        "",
        "## Per-gate best-case status",
        "",
        "(the best status achieved by any of that gate's equivalences — a gate can "
        "have some equivalences blocked and others ready)",
        "",
        "| Gate | Best status |",
        "|---|---|",
    ]
    for name in sorted(per_gate_status):
        lines.append(f"| `{name}` | {per_gate_status[name]} |")

    lines += ["", "## Examples by status", ""]
    for status in ("direct", "derived", "needs_convention_check", "needs_def"):
        lines.append(f"**{status}**: " + ", ".join(by_status_examples[status]))
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
