"""
generate_lean.py

Consumes data/equivalences.json (produced by extract_equivalences.py) and
leanquantum_mapping.py, and emits lean/QiskitEquiv/Generated.lean.

Every equivalence becomes exactly one Lean declaration, but WHICH kind of
declaration depends on whether every gate involved has a trustworthy
LeanQuantum mapping:

  - all gates "direct"                      -> `lemma ... := by sorry`
                                                (TODO_PROOF: ready to attempt)
  - any gate "derived"                      -> `lemma ... := by sorry`
                                                (TODO_PROOF, needs a helper
                                                lemma cited in a comment)
  - any gate "needs_convention_check"        -> emitted as a comment block,
                                                not a real lemma, so nobody
                                                can accidentally `sorry`
                                                their way past an unverified
                                                ordering assumption
  - any gate "needs_def"                     -> emitted as a comment noting
                                                exactly which primitive is
                                                missing

This asymmetry is deliberate: a `sorry` in Lean is a visible, trackable
proof obligation (CI can count them). A confidently-wrong `lemma` that
compiles because the statement itself encodes a wrong convention is far
worse, because it *looks* verified. Anything not numerically verified
stays as a comment, never a lemma statement.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from leanquantum_mapping import GateMapping, resolve

import math
from fractions import Fraction

# Denominators actually used by the standard gate library's angle constants
# (halves, quarters, eighths, thirds, sixths, twelfths of pi). Bare float
# literals like "3.141592653589793" are exact RATIONAL numbers as Lean ℝ
# literals -- NOT Real.pi, which is transcendental. Stating a lemma with
# the decimal literal in place of `π` would therefore be substituting a
# different (false) claim under a similar-looking name. Every angle that
# is a recognizable rational multiple of pi gets rewritten symbolically;
# anything else is left as a decimal AND flagged, since decimal literals
# are only safe for angles that are genuinely meant to be exact rationals
# (there are none among the standard gates -- all angles are pi-multiples).
_PI_DENOMS = [1, 2, 3, 4, 6, 8, 12, 16, 32]


def pi_aware_literal(value: str) -> str:
    try:
        x = float(value)
    except ValueError:
        return value  # already symbolic (e.g. "0.5*θ"), leave untouched
    if abs(x) < 1e-12:
        return "0"
    ratio = x / math.pi
    for d in _PI_DENOMS:
        n = ratio * d
        rn = round(n)
        if abs(n - rn) < 1e-9 and rn != 0:
            frac = Fraction(rn, d)
            num, den = frac.numerator, frac.denominator
            sign = "-" if num < 0 else ""
            num = abs(num)
            if den == 1:
                return f"{sign}({num} * π)" if num != 1 else f"{sign}π"
            core = f"π / {den}" if num == 1 else f"({num} * π / {den})"
            return f"{sign}{core}"
    # Not a recognizable pi-multiple -- flag it loudly rather than emit a
    # silently-wrong decimal literal.
    return f"(sorryAx ℝ /- UNRECOGNIZED ANGLE {value}, NOT a clean pi-multiple, needs manual review -/)"


HEADER = '''\
/-
  Generated by extractor/generate_lean.py from data/equivalences.json.
  DO NOT EDIT BY HAND -- edit leanquantum_mapping.py or the extraction
  pipeline instead and regenerate.

  Source: Qiskit {qiskit_version} StandardEquivalenceLibrary
  Generated: {extracted_at}
  {gate_count} gates / {equivalence_count} equivalences considered.

  See notes/coverage.md for a human-readable summary of what's proved,
  what's `sorry`, and what's blocked on a missing LeanQuantum definition.
-/

import Quantumlib.Data.Gate.Basic
import Quantumlib.Data.Gate.Rotate
import Quantumlib.Data.Gate.PhaseShift
import Quantumlib.Data.Gate.Pauli.Defs
import Quantumlib.Data.Gate.Equivs

namespace QiskitEquiv

open Real (pi)
local notation "π" => Real.pi

'''


def substitute_params(expr: str, params: list[str]) -> str:
    """Fill {p0}, {p1}, ... placeholders with extracted parameter strings.

    Qiskit parameter expressions come through as Python-syntax strings
    (e.g. "0.5*θ", "(-0.5)*θ"); Lean uses the same infix operators for
    ℝ, so a direct substitution is valid for the linear expressions the
    standard library actually uses. This would need a real expression
    parser if a future equivalence used something more exotic.
    """
    out = expr
    for i, p in enumerate(params):
        cleaned = p.replace("(-0.5)*", "-0.5*")
        # if it's a bare numeric literal (no symbolic variable), route
        # through the pi-multiple detector rather than paste the decimal.
        try:
            float(cleaned)
            cleaned = pi_aware_literal(cleaned)
        except ValueError:
            pass  # symbolic expression like "0.5*θ" -- leave as-is
        out = out.replace(f"{{p{i}}}", cleaned)
    return out


def gate_call_to_lean(instr: dict, all_mappings: dict[str, GateMapping]) -> tuple[str | None, GateMapping]:
    mapping = resolve(instr["name"])
    if mapping.lean_expr is None:
        return None, mapping
    return substitute_params(mapping.lean_expr, instr["params"]), mapping


def build_lemma_name(gate: dict, eq: dict) -> str:
    base = gate["name"]
    return f"{base}_equiv_{eq['index']}"


def render_equivalence(gate: dict, eq: dict) -> str:
    lemma_name = build_lemma_name(gate, eq)
    worst_status = "direct"
    status_rank = {"direct": 0, "derived": 1, "needs_convention_check": 2, "needs_def": 3}
    exprs = []
    notes = []

    for instr in eq["instructions"]:
        expr, mapping = gate_call_to_lean(instr, {})
        if status_rank[mapping.status] > status_rank[worst_status]:
            worst_status = mapping.status
        if mapping.note:
            notes.append(f"{instr['name']}: {mapping.note}")
        exprs.append((instr["name"], expr, mapping.status))

    source_mapping = resolve(gate["name"])
    if status_rank.get(source_mapping.status, 3) > status_rank[worst_status]:
        worst_status = source_mapping.status
    if source_mapping.note:
        notes.append(f"{gate['name']} (source): {source_mapping.note}")

    # de-duplicate while preserving first-seen order (repeated gates in a
    # circuit, e.g. h() appearing four times, would otherwise repeat the
    # same note four times)
    seen: set[str] = set()
    deduped_notes = []
    for n in notes:
        if n not in seen:
            seen.add(n)
            deduped_notes.append(n)
    notes = deduped_notes

    lines: list[str] = []
    lines.append(f"-- {gate['name']} equivalence #{eq['index']} "
                 f"({len(eq['instructions'])} instruction(s), global_phase={eq['global_phase']})")

    if worst_status in ("needs_def", "needs_convention_check"):
        reason = "missing LeanQuantum definition(s)" if worst_status == "needs_def" \
            else "unverified qubit-ordering / convention"
        lines.append(f"-- BLOCKED ({reason}) -- not emitted as a lemma, see notes above.")
        for n in notes:
            lines.append(f"--   * {n}")
        circuit_desc = " ; ".join(f"{n}({', '.join(p) if (p:=i['params']) else ''})" for i, n in
                                   [(i, i['name']) for i in eq['instructions']])
        lines.append(f"-- circuit: {circuit_desc}")
        return "\n".join(lines) + "\n"

    # direct or derived: emit a real (sorry'd) lemma statement.
    src = source_mapping.lean_expr or "sorry"  # source is guaranteed non-None here
    src_params = [str(p) for p in gate.get("source_params", [])]
    lean_src_params = ", ".join(f"({p} : ℝ)" for p in src_params)
    binder = f" {lean_src_params}" if lean_src_params else ""
    if src_params:
        # source_params are the SYMBOLIC names Qiskit used (e.g. θ); the
        # matched LeanQuantum expr already uses {p0} substitution keyed
        # off the SAME positions in the *equivalent circuit's* gates, but
        # the LHS gate itself also needs its own symbolic param named.
        src_expr = source_mapping.lean_expr
        for i, p in enumerate(src_params):
            src_expr = src_expr.replace(f"{{p{i}}}", p)
    else:
        src_expr = src

    rhs_terms = " * ".join(e for _, e, _ in exprs if e is not None)

    gp_str = eq.get("global_phase", "0.0")
    try:
        gp_val = float(gp_str)
    except ValueError:
        gp_val = None  # symbolic global phase (rare, but don't silently drop it)

    if gp_val is not None and abs(gp_val) > 1e-12:
        phase_lit = pi_aware_literal(gp_str)
        rhs_terms = f"(Complex.exp ({phase_lit} * Complex.I)) • ({rhs_terms})"
    elif gp_val is None:
        rhs_terms = f"(Complex.exp (({gp_str}) * Complex.I)) • ({rhs_terms})"
        notes.append(f"symbolic global_phase '{gp_str}' -- verify this substitution parses.")

    status_tag = "TODO_PROOF (direct mapping)" if worst_status == "direct" else "TODO_PROOF (derived -- needs helper lemma first)"

    lines.append(f"-- {status_tag}")
    for n in notes:
        lines.append(f"--   note: {n}")
    lines.append(f"lemma {lemma_name}{binder} :")
    lines.append(f"    {src_expr} = {rhs_terms} := by")
    lines.append("  sorry")
    return "\n".join(lines) + "\n"


def main() -> None:
    data_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("data/equivalences.json")
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("lean/QiskitEquiv/Generated.lean")

    manifest = json.loads(data_path.read_text())

    body_parts = [
        HEADER.format(
            qiskit_version=manifest["qiskit_version"],
            extracted_at=manifest["extracted_at"],
            gate_count=manifest["gate_count"],
            equivalence_count=manifest["equivalence_count"],
        )
    ]

    counts = {"direct": 0, "derived": 0, "needs_convention_check": 0, "needs_def": 0}

    for gate in manifest["gates"]:
        section = [f"/- ===== {gate['name']} ({gate['num_qubits']} qubit(s)) ===== -/\n"]
        for eq in gate["equivalences"]:
            rendered = render_equivalence(gate, eq)
            section.append(rendered)
            # crude re-derivation of status for the summary count
            if "BLOCKED (missing" in rendered:
                counts["needs_def"] += 1
            elif "BLOCKED (unverified" in rendered:
                counts["needs_convention_check"] += 1
            elif "TODO_PROOF (direct" in rendered:
                counts["direct"] += 1
            else:
                counts["derived"] += 1
        body_parts.append("\n".join(section))

    body_parts.append("\nend QiskitEquiv\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(body_parts))

    total = sum(counts.values())
    print(f"Wrote {out_path} ({total} equivalences)")
    print(f"  direct (ready to attempt proof) : {counts['direct']}")
    print(f"  derived (needs helper lemma)     : {counts['derived']}")
    print(f"  blocked, convention check needed : {counts['needs_convention_check']}")
    print(f"  blocked, missing LeanQuantum def : {counts['needs_def']}")


if __name__ == "__main__":
    main()
